#!/bin/bash

#PBS -lwalltime=06:00:00
#PBS -lselect=1:ncpus=32:mem=8gb:mpiprocs=1:ompthreads=32

set -e

lscpu

JOB_NAME=pic_test

module load gcc/10.2.0
module load mpi
module load hdf5/1.10.5-parallel
module load anaconda3/personal

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib

OUTDIR=$EPHEMERAL/$JOB_NAME/$PBS_JOBID
mkdir -p $OUTDIR
cd $OUTDIR

mpiexec smilei_sub $HOME/namelists/${JOB_NAME}.py
