#!/bin/bash

#PBS -lwalltime=04:00:00
#PBS -lselect=2:ncpus=32:mem=16gb:mpiprocs=8:ompthreads=4

set -e

JOB_NAME=a_0_basic

module load gcc/10.2.0
module load mpi
module load hdf5/1.10.5-parallel
module load anaconda3/personal

echo "MODULES LOADED"

source ~/.bashrc

conda activate smilei

echo "SMILEI ACTIVATED"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib

OUTDIR=$EPHEMERAL/$JOB_NAME/$PBS_JOBID
mkdir -p $OUTDIR
cd $OUTDIR

echo "FOLDERS CREATED"

lscpu > cpu.txt

echo "INVOKING JOB"
mpirun -n 1 python ~/supervisors/basic_supervisor.py $JOB_NAME
